// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0cqziSTjiQpMLNkb7o_Hzg1xlL3weqFU',
    appId: '1:412210175235:web:187b84f307bdba61735d36',
    messagingSenderId: '412210175235',
    projectId: 'shertified-ssers',
    authDomain: 'shertified-ssers.firebaseapp.com',
    storageBucket: 'shertified-ssers.firebasestorage.app',
    measurementId: 'G-REPVM0H68S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe9a3f-tdyI-5_duNc38NEj5YWDbjOrgY',
    appId: '1:412210175235:android:170476e29477377f735d36',
    messagingSenderId: '412210175235',
    projectId: 'shertified-ssers',
    storageBucket: 'shertified-ssers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqHzqbDBpv9fma9oytUZiu3Zbc2QZ_O0s',
    appId: '1:412210175235:ios:fec58ba243c45fbe735d36',
    messagingSenderId: '412210175235',
    projectId: 'shertified-ssers',
    storageBucket: 'shertified-ssers.firebasestorage.app',
    iosBundleId: 'com.ennius5.ssers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqHzqbDBpv9fma9oytUZiu3Zbc2QZ_O0s',
    appId: '1:412210175235:ios:5b15b54d63dfc9da735d36',
    messagingSenderId: '412210175235',
    projectId: 'shertified-ssers',
    storageBucket: 'shertified-ssers.firebasestorage.app',
    iosBundleId: 'com.example.ssers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0cqziSTjiQpMLNkb7o_Hzg1xlL3weqFU',
    appId: '1:412210175235:web:ae3b7d84a1088ad2735d36',
    messagingSenderId: '412210175235',
    projectId: 'shertified-ssers',
    authDomain: 'shertified-ssers.firebaseapp.com',
    storageBucket: 'shertified-ssers.firebasestorage.app',
    measurementId: 'G-TPLXJSRTTE',
  );
}
